---

###
## Tasks to configure SNMP on the servers.
#

- name: Check snmp directory permissions
  file: 
    path: /etc/snmp 
    owner: root 
    group: root 
    mode: 0750 
    state: directory
  tags: 
      - snmp_dir

- name: Install snmpd configuration
  template: 
    src: tempates/snmpd.conf.tmpl
    dest: /etc/snmp/snmpd.conf
    mode: 0640 
    owner: root 
    group: root 
    backup=true
  register: config
  notify: Restart snmp
  tags:
      - snmp_conf

#- name: Install snmpd options (OEL6, OEL7)
#  copy: src={{syscfg}}/snmpd
#        dest=/etc/sysconfig/snmpd
#        mode=644 owner=root group=root backup=true
#  register: options
#  when: ansible_distribution_major_version|int >= 6
#  tags:
#      - snmp_options
